services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # vm-be Tailscale IP: 100.116.57.50
        # Untuk production, ganti dengan: https://api.yourdomain.com/api
        NEXT_PUBLIC_API_URL: http://100.116.57.50/api
    container_name: nopmo_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
