services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # VM-Backend IP: 192.168.56.11
        # Untuk production, ganti dengan: https://api.yourdomain.com/api
        NEXT_PUBLIC_API_URL: http://192.168.56.11/api
    container_name: internetsehat_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
