services:
  postgres:
    image: postgres:16-alpine
    container_name: nopmo_db
    restart: unless-stopped
    env_file: .env
    ports:
      # Bind ke IP Tailscale vm-db, tidak expose ke publik
      - "100.111.166.88:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
